### ISSUE TITLE
 fatal error when it errs on the login credentials

### ISSUE THREAD

**Issue by moises94** [dawguk/php-garmin-connect#10]
Hello,
first thank a lot for your work.
Sorry for my english but i m french.
when I'm wrong about connection information
a receive a fatal error.
and i break my site.
Fatal error: Uncaught dawguk\GarminConnect\exceptions\AuthenticationException: Looks like the authentication failed in src/dawguk/GarminConnect.php:143 Stack trace: #0 src/dawguk/GarminConnect.php(76): dawguk\GarminConnect->authorize('xxx...', 'xxx') #1 modules/page/choix_app.php(188): dawguk\GarminConnect->__construct(Array) #2 index.php(34): include('/var/www/html/s...') #3 {main} thrown in /src/dawguk/GarminConnect.php on line 143

can you help me.

**Comment by dawguk** [comment]
Salut! Votre anglais est aussi bon que mon français, donc ne vous inquiétez pas!

It looks like you aren't putting your code in a try {} catch () block - so first you need to try that.

```php
<?php
try {
   // Your code here
} catch (Exception $obj_exception) {
   echo "Oops! " . $obj_exception->getMessage();
}
```

**Comment by moises94** [comment]
salut,

Merci beaucoup.
Thanks

--
Quaresma

2016-10-03 16:13 GMT+02:00 David Wilcock <notifications@github.com>:
