### ISSUE TITLE
getDataFile endpoint has been retired

### ISSUE THREAD

**Issue by Thorpe89** [dawguk/php-garmin-connect#11]
When I view the URL associated with getting endpoints (https://connect.garmin.com/proxy/activity-service-1.2/tcx/activity/12345?full=true) 

I receive: "The requested endpoint is retired". Has this endpoint been replaced or is it no longer to get the tcx, gpx or kml file?

**Comment by dawguk** [comment]
Hi,

I've scraped the new download URL for this service from the Garmin Connect website (oops), have tested it with all TCX, GPX and KML files, and they all work OK. As a result, this issue is fixed in release v1.0.3

Cheers!
