### ISSUE TITLE
can not get activities back (using v1.0.2)

### ISSUE THREAD

**Issue by SunboX** [dawguk/php-garmin-connect#17]
I've a Garmin vivosmart HR and it's syncing it's data with Garmin Connect. If I try to get the recorded activities by calling `getActivityList()`, all I get back is this:

```
stdClass Object
(
    [results] => stdClass Object
        (
            [search] => stdClass Object
                (
                    [query] => stdClass Object
                        (
                            [filters] => stdClass Object
                                (
                                    [userId] => 51301577
                                    [userId_oper] => =
                                )

                            [sortOrder] => DESC
                            [sortField] => activitySummaryBeginTimestampGmt
                            [activityStart] => 0
                            [activitiesPerPage] => 10
                            [explore] => false
                            [ignoreUntitled] => false
                            [ignoreNonGPS] => false
                        )

                    [currentPage] => 1
                    [totalFound] => 0
                    [totalPages] => 0
                )

        )

)
```

So, what's wrong?

**Comment by SunboX** [comment]
Seems this is related to https://github.com/kjkjava/garmin-connect-export/issues/20

**Comment by dawguk** [comment]
Hi SunboX

Unfortunately I don't have access to any heart rate data - can you confirm if there is a service that allows you to download your wellness data, and which URL that would be? I may be able to figure out which URL to grab the data from, in that case.

Thanks,
Dave

**Comment by SunboX** [comment]
Hi Dave,

I'm more interested in "steps" count than the heart rate. The url should look something like this:
https://connect.garmin.com/modern/proxy/download-service/files/wellness/2016-08-28

Don't ask me, why the tracker reports as "wellness". I tried https://www.fitnesssyncer.com/ that can fetch the data, but I also have to choose "Garmin (Wellness)" instead of "Garmin (Sports)" there.

greetings,
André

**Comment by dawguk** [comment]
Forgive me, I don't have any wellness data so can't retrieve any. From the URL that you have provided, do you retrieve a good set of expected data?

Also, is it just provided by date, rather than an ID (as per your URL)?

**Comment by dawguk** [comment]
Closing due to the age of this issue. If this persists, please raise a new issue.
