### ISSUE TITLE
Getting 302 response on trying to get activities list.

### ISSUE THREAD

**Issue by hjelmdal** [dawguk/php-garmin-connect#2]
Oops: An unexpected response code was found: 302

Happens on every example call :-(

Great work, btw :-)

**Comment by dawguk** [comment]
Howdy,

It appears that Garmin has changed their "API" endpoints. I'll see if there is any documented changes or a workaround and update accordingly.

**Comment by dawguk** [comment]
It does appear that the API can no longer GET the activity list over port 80, but other endpoints work just fine on port 80. This _may_ be some weird web service misconfiguration on Garmin's side, so I'll leave the endpoint URLs as they are for now.

Commit 20eef78 fixes this issue. It appears to be a combination of an argument-list-fail on my part, and the endpoint issuing a 302 redirect.

**Comment by hjelmdal** [comment]
wow - that was a fast reply! thank you so much! I can be mistaking, but I think the problem is the same for activity types (which is not that important for me) - Thank you so much for you effort!
