### ISSUE TITLE
Can't get summary of newwest activities

### ISSUE THREAD

**Issue by Dhofca** [dawguk/php-garmin-connect#22]
Hello,

I have problem with getting summary of activities using `getActivitySummary($intActivityID)` which are done after 1 of August (probably). I think Garmin changed something in their API because:

This one was created 25.07 and it works:
https://connect.garmin.com/modern/proxy/activity-service/activity/1875872198

This one was created 03.08 and it's the same type of activity:
https://connect.garmin.com/modern/proxy/activity-service/activity/1893087702

as you can see, response is:
{"message":"HTTP 403 Forbidden","error":"WebApplicationException"}

Nothing was changed in privacy settings in Garmin account. Activity made 29.07 works too. Maybe you faced similar issue earlier?

Cheers, 
Maciej.

**Comment by dawguk** [comment]
Closing this due to the age of the issue. If this problem still persists, please raise a new issue.
