### ISSUE TITLE
Getting all activities or just selected ones

### ISSUE THREAD

**Issue by Toubef** [dawguk/php-garmin-connect#24]
Hi,

ok so I got this working now. And if I use the $obj_results = $objGarminConnect->getActivityList(0, 1);
it will show me a result and I have a total of 142 activities.
So when I try to add a bigger limit like $obj_results = $objGarminConnect->getActivityList(0, 150);
it gives an http 400 error.

Any way to only list / print only selected activities like cycling?

Br.
Toube

**Comment by dawguk** [comment]
The ability to now only retrieve activities by activity type has been added since release v1.2.0 - please check the README and example for instructions.
