### ISSUE TITLE
Get only Old Activities (getActivityList)

### ISSUE THREAD

**Issue by cabby26** [dawguk/php-garmin-connect#25]
I get only Activities before 2018-03-18

**Comment by Joen7** [comment]
Same here, though my last activity is from 2018-03-21. I guess this is on the Garmin side. Maybe they have several servers, one for normal web traffic and one for 'us', which is not continuously in sync.
When I login via Garmin Connect manually, I do get the latest activities using this url:
https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?limit=5&start=0

**Comment by dawguk** [comment]
I've had a look at this - Garmin have changed a bunch of URLs and some of the authentication responses. I have an early working version that I'm about to PR in, but it has limited working scope currently.

**Comment by dawguk** [comment]
The changes are now in master, so pull it in and let me know if authentication now works. You might need to manually remove any cookie cache that you previously had.
