### ISSUE TITLE
login has stopped working

### ISSUE THREAD

**Issue by cabby26** [dawguk/php-garmin-connect#26]
503 Service Unavailable

**Comment by dawguk** [comment]
I've had a look at this - Garmin have changed a bunch of URLs and some of the authentication responses. I have an early working version that I'm about to PR in, but it has limited working scope currently.

**Comment by dawguk** [comment]
The changes are now in master, so pull it in and let me know if authentication now works. You might need to manually remove any cookie cache that you previously had.

**Comment by cabby26** [comment]
It works. Thanks :)
