### ISSUE TITLE
Garmin API endpoints have changed - some help is required

### ISSUE THREAD

**Issue by dawguk** [dawguk/php-garmin-connect#28]
I have recently found that Garmin have deprecated a lot of the API endpoints that were being used in this library. I have snooped enough to fix the authentication mechanism, and the ability to get activities, but that's about it at the minute. I would appreciate help from anyone in identifying the other URLs that need to be updated. The are currently for the following methods:

- getActivityTypes()
- getActivitySummary()
- getActivityDetails()
- getExtendedActivityDetails()
- getDataFile()

The way that I captured authentication and getActivityList(), was to login to Garmin Connect in Google Chrome with Developer Tools open, hit the Record button in the Network tab, and filter all XHR requests - these are invariable the API calls being made at various points.

**Comment by cabby26** [comment]
Look at the Fork of klorie

**Comment by klorie** [comment]
My fork was also a work in progress, it's already obsolete...

**Comment by AByGCreation** [comment]
Hello, have you seen my post here : https://github.com/AByGCreation/php-garmin-connect/tree/patch-2, is this will help you ?

**Comment by dawguk** [comment]
Hi,

Can you submit a pull request for this work and I'll take a look!

Cheers, Dave

**Comment by hmsuchier** [comment]
Hi,
 Thanks for your work that allowed me to start a js connector for  [Cozy](https://cozy.io/fr/), a french decentralized cloud project the connector project is [here](https://github.com/hmsuchier/cozy-konnector-garmin). Are you still interested in pull requests concerning route changes?
Thanks

**Comment by dawguk** [comment]
Most endpoints are now working, apart from the endpoint URL used in `getActivityDetails()` method - I'm still unable to get to the bottom of this one.
