### ISSUE TITLE
issues with authentication process

### ISSUE THREAD

**Issue by mgnwong** [dawguk/php-garmin-connect#31]
Authorize function is returning the error "Authentication failed - please check your credentials" because the login form needs a csrf value, apparently. Has anyone gone over this?

**Comment by fulmar2** [comment]
I am having this issue as well - since about 2 or 3 days ago.

**Comment by JLTRY** [comment]
same issue for me let me know if any progress

**Comment by Yngve0** [comment]
It seems like they not only added a CSRF-value, but also some other changes in the SSO-form.

Seems like Garmin dont see the value of this opensource-addOns. :(

**Comment by cabby26** [comment]
same Problem

**Comment by dawguk** [comment]
Thanks all. I'm current on anual leave, but should be able to look at this soon. I'll need to decompose the Garmin login screens and see if there's anything we can do here. However, the mention of CRF doesn't fill me with hope, especially if they've done it right.

**Comment by raven-ie** [comment]
@dawguk the referenced issued have a working fix in place.

**Comment by dawguk** [comment]
Yep, I posted a request to take a look at their PR and see if we can do the same thing. I'll have a play later ...

**Comment by dawguk** [comment]
This is now resolved in pull request #34

**Comment by dawguk** [comment]
Forgot to mention, thanks to @JLTRY for the triggerig of this fix, I got my lazy-self back to the computer to resolve.
