### ISSUE TITLE
getActivitySummary() doesn't work

### ISSUE THREAD

**Issue by cabby26** [dawguk/php-garmin-connect#36]
Oops: An unexpected response code was found: 410
[url] => https://connect.garmin.com/proxy/activity-service-1.3/json/activity/3599xxxx
    [content_type] => text/html
    [http_code] => 410
    [header_size] => 662
    [request_size] => 369
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.31838
    [namelookup_time] => 0.000137
    [connect_time] => 0.028485
    [pretransfer_time] => 0.113492
    [size_upload] => 0
    [size_download] => 33
    [speed_download] => 103
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0.318213
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 104.17.3.69
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 192.168.178.51
    [local_port] => 55690

**Comment by gear4dave** [comment]
Yep, this looks to have changed too. I'll see what I can find out.

**Comment by dawguk** [comment]
Thanks for the report. I have fixed, pushed and tagged a new release (v1.1.2), which resolve this issue. There is still an outstanding issue with the endpoint URL used in getActivityDetails() method, so until that's fixed (or deprecated, we'll see) I would advise using the getExtendedActivityDetails() method for retrieving full activity details.
