### ISSUE TITLE
getActivityList returns 403 error

### ISSUE THREAD

**Issue by adamm88** [dawguk/php-garmin-connect#4]
Every function is working except the getActivityList. The service returns:

> An unexpected response code was found: 403

Every other function is working and authentication is also working

**Comment by dawguk** [comment]
Hi,

This is an interesting one. When signing-in to the web interface, and accessing the URL that's used directly in the getActivityList method:

https://connect.garmin.com/proxy/activity-search-service-1.0/json/activities

... I get the expected response. This does seem like there is an authentication bug for this particular call, but I'm pretty certain that it's not doing anything different to the other calls.

Can I ask you to sign-in to the Garmin Connect website (https://connect.garmin.com) and then access the above URL - let me know what you get back?

**Comment by dawguk** [comment]
With that said, I just took a guess and tried the following URL:

https://connect.garmin.com/proxy/activity-search-service-1.2/json/activities

... I get a response that contains near-enough the same data, but in a different format. Can you see if you have any luck with that one?

**Comment by adamm88** [comment]
Hey, thanks for such a fast response.
Yes, when I log in to Garmin Connect and go on url you provided, then I see
results.
But through your library I receive 403. If this will work from code then it
would be great.

2016-03-22 11:19 GMT+01:00 David Wilcock < notifications@github.com > :
With that said, I just took a guess and tried the following URL:

https://connect.garmin.com/ proxy/activity-search-service- 1.2/json/activities

... I get a response that contains near-enough the same data, but in a different
format. Can you see if you have any luck with that one?

**Comment by dawguk** [comment]
I have just cloned this exact copy, and run the example (changed it to getActivityList), and I am able to get a response with no issue:

```
stdClass Object
(
    [results] => stdClass Object
        (
            [activities] => Array
                (
                    [0] => stdClass Object
                        (
                            [activity] => stdClass Object
                                (
                                    [activityId] => 593520370
                                    [activityName] => stdClass Object
                                        (
                                            [value] => Untitled
                                        )

                                    [activityDescription] => stdClass Object
                                        (
                                            [value] => 
                                        )

                                    [locationName] => stdClass Object
                                        (
                                            [value] => 
                                        )

                                    [userId] => 6837892

```
etc.

If you adapt the example in the same way, does this work?

**Comment by adamm88** [comment]
I did this, and get the same result: 403

2016-03-22 11:38 GMT+01:00 David Wilcock < notifications@github.com > :
I have just cloned this exact copy, and run the example (changed it to
getActivityList), and I am able to get a response with no issue:

stdClass Object
(
    [results] => stdClass Object
        (
            [activities] => Array
                (
                    [0] => stdClass Object
                        (
                            [activity] => stdClass Object
                                (
                                    [activityId] => 593520370
                                    [activityName] => stdClass Object
                                        (
                                            [value] => Untitled
                                        )

                                    [activityDescription] => stdClass Object
                                        (
                                            [value] => 
                                        )

                                    [locationName] => stdClass Object
                                        (
                                            [value] => 
                                        )

                                    [userId] => 6837892



etc.

If you adapt the example in the same way, does this work?

**Comment by wadsapps** [comment]
Excuse me but I have the same problem .
I changed the URL https://connect.garmin.com/proxy/activity-search-service-1.2/json/activities but I still get error 403 .
The code: 
public function getActivityList($intStart = 0, $intLimit = 10) {

      $arrParams = array(
         'start' => $intStart,
         'limit' => $intLimit
      );

      $strResponse = $this->objConnector->get('https://connect.garmin.com/proxy/activity-search-service-1.2/json/activities', $arrParams, TRUE);
      //$strResponse = $this->objConnector->get('https://connect.garmin.com/proxy/activity-search-service-1.0/json/activities', $arrParams, TRUE);
      if ($this->objConnector->getLastResponseCode() != 200) {
         throw new UnexpectedResponseCodeException($this->objConnector->getLastResponseCode());
      }
      $objResponse = json_decode($strResponse);
      return $objResponse;
   }

the example.php
<?php
require_once '../vendor/autoload.php';

$arrCredentials = array(
'username' => 'antodaph@xxxx.com',
'password' => 'MDPxxx',
'identifier' => '1'
);

try {
      $objGarminConnect = new \dawguk\GarminConnect($arrCredentials);
      $obj_results = $objGarminConnect->getActivityList(0, 1);
      print_r($obj_results);
   } catch (Exception $objException) {
      echo "Oops: " . $objException->getMessage();
   }
?>

if I am connected and I test the URL from the browser , it works
thank you in advance for your help
.

**Comment by dawguk** [comment]
Hi,

This is a very interesting issue, because it doesn't make any real sense - the authentication method should effectively simulate the same authentication that you would perform in a browser, and the resulting URL should work in the same way that it also works in the browser, but this seems to not be the case.

Can I ask you to perform the test with the following URL instead:

https://connect.garmin.com/modern/proxy/activity-search-service-1.2/json/activities

Let me know if that makes any difference.

**Comment by wadsapps** [comment]
Hi,

i changed the url.
public function getActivityList($intStart = 0, $intLimit = 10) {

      $arrParams = array(
         'start' => $intStart,
         'limit' => $intLimit
      );

      //$strResponse = $this->objConnector->get('https://connect.garmin.com/proxy/activity-search-service-1.0/json/activities', $arrParams, TRUE);
      $strResponse = $this->objConnector->get('https://connect.garmin.com/modern/proxy/activity-search-service-1.2/json/activities', $arrParams, TRUE);
      if ($this->objConnector->getLastResponseCode() != 200) {
         throw new UnexpectedResponseCodeException($this->objConnector->getLastResponseCode());
      }
      $objResponse = json_decode($strResponse);
      return $objResponse;
   }

But the response :
Oops: An unexpected response code was found: 403

**Comment by dawguk** [comment]
Can you give me some details of:

Operating System (+version) and PHP Version being used please? Also, any other information you think could be relevant?

**Comment by dawguk** [comment]
Might also be useful to know when you registered the Garmin account, how many activities you have, are they public ( ? ), what country you are from, timezone etc. I know these all sound like odd questions, I'll just need to test a few silly scenarios before I can discount them.

The reality is, Garmin don't endorse connecting to their APIs in this way, because it's undocumented, non-standard, not supported, etc. and I have no idea if they lock certain things down based on user credentials and / or criteria.

**Comment by wadsapps** [comment]
Hi,
i tested the windows pc and php is version 5.5.12 and the other the version php is 5.4.24
it's no ok.

If i test on ovh with the version php 5.4.24 it's ok.

why on the windows by wampserver it's no ok ?

**Comment by wadsapps** [comment]
hi,
i tested on the server windows by iis and it's no ok.
i I would like to run your program on my windows's server. it's possible ?

**Comment by dawguk** [comment]
It might be related to the CURL version that is preventing the cookie from being read correctly, it might even be the cookie storage location, as it's currently being set to "/tmp/", which obviously doesn't exist under Windows.

I don't have Windows here, so can I ask you to perform some tests for me?

In the GarminConnect/Connector.php, there is a method called refreshSession(). Can you change that method for the following

```php
   public function refreshSession() {
      $this->objCurl = curl_init();
      $this->arrCurlOptions[CURLOPT_COOKIEJAR] = sys_get_temp_dir() . $this->strUniqueIdentifier;
      $this->arrCurlOptions[CURLOPT_COOKIEFILE] = sys_get_temp_dir() . $this->strUniqueIdentifier;
      curl_setopt_array($this->objCurl, $this->arrCurlOptions);
   }
```

... and try your test again - let me know the outcome?

**Comment by wadsapps** [comment]
Hi,
on my pc with wampserver it's ok.
But on my server on the IIS, it's no ok. grrrr
the sys_get_temp_dir() is c:\windows\temp

**Comment by dawguk** [comment]
Can you output the value of sys_get_temp_dir() on both IIS and wampserver please?

**Comment by wadsapps** [comment]
the sys_get_temp_dir() is c:\windows\temp on the two machines

**Comment by dawguk** [comment]
One last try before I head to bed!

Can you try changing the following lines:

```php
$this->arrCurlOptions[CURLOPT_COOKIEJAR] = sys_get_temp_dir() . DIRECTORY_SEPARATOR . $this->strUniqueIdentifier;
$this->arrCurlOptions[CURLOPT_COOKIEFILE] = sys_get_temp_dir() . DIRECTORY_SEPARATOR . $this->strUniqueIdentifier;
```

... any luck with that?

**Comment by wadsapps** [comment]
YYYYYYESSSSS.
it's good.
your are the best.
thanks and thanks again

**Comment by wadsapps** [comment]
hi,
the last question.
how clear the session or the classes?
Because when i test again the example.php and i change the user, the page display always the same information

**Comment by dawguk** [comment]
I have pushed out an update that should resolve all of the issues here, which includes the user switching query.

Please take a look at the example.php script for sample.

(There is no longer a requirement to specify an identifier in your credentials array)
