### ISSUE TITLE
Even more data?

### ISSUE THREAD

**Issue by AnneWielis** [dawguk/php-garmin-connect#42]
Hi there, 

activity Data is fine and i love it. But would be even more interested in 
- sleep quality
- weight
- stress Level 

and so on.

Any chance to query that? I'd be happy to implement it myself and make it available for pull, but i lack the API documentation for reaearch.

**Comment by AnneWielis** [comment]
Looks like they're writing the data there:

https://github.com/jaroslawhartman/withings-garmin-v2

But can't quite get the point on it.

**Comment by Raistlfiren** [comment]
You should be able to do this by hitting the following endpoints:

- https://connect.garmin.com/modern/proxy/wellness-service/wellness/dailySleeps?limit=10&start=1
- https://connect.garmin.com/modern/proxy/wellness-service/wellness/dailyStress/2020-07-06
- https://connect.garmin.com/modern/proxy/weight-service/weight/dayview/2020-07-06

I don't keep track of weight and I am unsure of how to pull that information, but that might be a good starting point.

**Comment by AnneWielis** [comment]
OK, got the Weight. Are you interested in a pull request?

**Comment by dawguk** [comment]
> OK, got the Weight. Are you interested in a pull request?

Very much so, if you please!
