### ISSUE TITLE
Did anyone have this stop working today?

### ISSUE THREAD

**Issue by fulmar2** [dawguk/php-garmin-connect#46]
Hi guys - I've been using this great connector for a while, and noticed that it stopped working for me this morning.  Anyone have the same issue? Thanks.

**Comment by fulmar2** [comment]
Resolved.  Likely a mistake I made. Thanks!

**Comment by dawguk** [comment]
Glad to be of help! ;)

**Comment by fulmar2** [comment]
David -

Thanks so much for the code!  I think what actually happened is Garmin Connect went down for a bit; I just happened to be testing something else at that time, and after fretting for about 20 minutes, I came back, and it worked again.  Weird.

Thanks again,
Brian
