### ISSUE TITLE
 getDataFile fails with exception : an unexpected response code was found: 503

### ISSUE THREAD

**Issue by JLTRY** [dawguk/php-garmin-connect#6]
I have tried your API with
$objGarminConnect = new \dawguk\GarminConnect($this->credentials)
$objGarminConnect->getActivityList($i, 10);
//parse results find $activityid
$objGarminConnect->getDataFile(\dawguk\GarminConnect::DATA_TYPE_TCX, $activityId));
=> exception : An unexpected response code was found: 503

Note that it works if I change the line
//$strResponse = $this->objConnector->get("https://connect.garmin.com/proxy/activity-service-1.1/" . $strType . "/activity/" . $intActivityID . "?full=true");
//to
$strResponse = $this->objConnector->get("https://connect.garmin.com/proxy/activity-service-1.2/" . $strType . "/activity/" . $intActivityID . "?full=true");

**Comment by dawguk** [comment]
Hmm ... I wonder if Garmin are shutting down some of their old API endpoints.

Thanks for the heads-up - I'll update the URL in the library.

**Comment by dawguk** [comment]
Closed: URL updated, tested, all working. Thanks!

**Comment by PauloBronfox** [comment]
Hi,

I've got the same issue with the endpoint https://connect.garmin.com/proxy/activity-service-1.2/

Do you have an idea about how to update it ? 
I've tried something like https://connect.garmin.com/proxy/download-service/export/gpx/activity/xxx but it does not work :(

**Comment by JLTRY** [comment]
Yes you are right, today its seems to fail also with new url.
We have to find another workaround

**Comment by PauloBronfox** [comment]
Hi,

in function authorize, replace the code
      $this->objConnector->post('https://connect.garmin.com/post-auth/login', $arrParams, null, FALSE);
      if ($this->objConnector->getLastResponseCode() != 302) {
         throw new UnexpectedResponseCodeException($this->objConnector->getLastResponseCode());
      }

      // should only exist if the above response WAS a 302 ;)
      $strRedirectUrl = $this->objConnector->getCurlInfo()['redirect_url'];

      $this->objConnector->get($strRedirectUrl, null, null, TRUE);
      if ($this->objConnector->getLastResponseCode() != 302) {
         throw new UnexpectedResponseCodeException($this->objConnector->getLastResponseCode());
      }

by      
      $strResponse = $this->objConnector->post('https://connect.garmin.com/post-auth/login', $arrParams, null);
      // try to add additionnal request
      $this->objConnector->get("http://connect.garmin.com/modern");
      $this->objConnector->get("https://connect.garmin.com/legacy/session");

And then in function getDataFile:
      //$strResponse = $this->objConnector->get("https://connect.garmin.com/proxy/activity-service-1.3/" . $strType . "/activity/" . $intActivityID . "?full=true");
      $strResponse = $this->objConnector->get("https://connect.garmin.com/modern/proxy/download-service/export/" . $strType . "/activity/" . $intActivityID . "?full=true");

Should work. Just be careful with checkCookieAuth in constructor function that may prevent the update of authorization process
