### ISSUE TITLE
Oops: SSO prestart error (code: 0, message: )

### ISSUE THREAD

**Issue by PauloBronfox** [dawguk/php-garmin-connect#7]
Hello,

I've installed the API on my server. When I try to run the "full example", I get the following error:
Oops: SSO prestart error (code: 0, message: )

Can you provide some support please ?

Thanks

**Comment by PauloBronfox** [comment]
The problem comes from the checkCookieAuth that destroys the curl object if username is not set. 
I've modified it this way:
   private function checkCookieAuth() {
      if (strlen(trim($this->getUsername())) == 0) {
         $this->objConnector->cleanupSession();
         $this->objConnector->refreshSession(); // added this line
         return FALSE;
      } else {
         return TRUE;
      }
   }

It seems to work

**Comment by dawguk** [comment]
Hi,

Good find. Would you like to fork, change and make a pull request?

Thanks,
Dave

**Comment by PauloBronfox** [comment]
Hi,

I don't know how to do that :(

Pierre
