### ISSUE TITLE
An unexpected response code was found: 503

### ISSUE THREAD

**Issue by simotho** [dawguk/php-garmin-connect#8]
Hi,
I'm receiving this error everytime I try to get latest activities.

It has worked without problems until this wednesday.

Anyone that have same problem?

**Comment by dawguk** [comment]
Hi,

It looks as though Garmin have changed some of their API endpoints - as soon as I can figure out what the changes might be,  I'll update everything accordingly.

There is always a chance that Garmin have made these completely unavailable, because of this:

http://developer.garmin.com/garmin-connect-api/overview/

... and the fact that we're essentially circumventing their pay plan. We'll see.

Cheers,
Dave

**Comment by simotho** [comment]
Hi Dave,
Thanks for quick response.
Would be great, let's hope there is a solution on the problem.

**Comment by simotho** [comment]
Seems like the problem is because the /tcx/activity endpoint is retired.
If you can figured out where to find a new endpoint to grab the tcx, that would be awesome!

**Comment by simotho** [comment]
Maybe this can help finding the "problems"
https://github.com/kjkjava/garmin-connect-export/issues/18#issuecomment-243859319

**Comment by superpoi** [comment]
Hi
I've got the same issue, 
According to "kjkjava/garmin-connect-export#18 (comment)" I tried to add 

$this->objConnector->get('http://connect.garmin.com/modern');
$this->objConnector->get('https://connect.garmin.com/legacy/session');

to GarminConnect.php but it does'nt work ... Could you help me ?
Thanks

**Comment by dawguk** [comment]
Hi,

Is this still an issue?

Thanks,
Dave

**Comment by superpoi** [comment]
Hi Dave,
Yes is still an issue.
The new endpoint seems to be : https://connect.garmin.com/modern/proxy/download-service/export/gpx/activity/xxxxxxxxxxxx.
But when putting this URL on getDataFile function it does'nt work.
Thanks
Patrice

**Comment by dawguk** [comment]
Hi,

If you update to the latest release, this should now be fixed. The fixed line can be found at:

https://github.com/dawguk/php-garmin-connect/blob/master/src/dawguk/GarminConnect.php#L287

The URL that you provided is nearly correct, but with some trial and error, I nailed the correct URL.

Let me know how you get on.

Cheers,
Dave

**Comment by superpoi** [comment]
Hi Dave,
Thank you ! now it seems ok for download an activity.
But on the same way "https://connect.garmin.com/proxy/activity-service-1.3/json/activityDetails/" used on getActivitySummary function seems to be retired.
I tried to use https://connect.garmin.com/modern/proxy/activity-service/activity/ instead ( it is working on an internet browser) but I got an 403 error : Access denied.
Do you get the same error ?
Thanks

**Comment by dawguk** [comment]
Hi,

This has been resolved in 6f9fe5a!

Thanks,
Dave
